scrape_configs:
  - job_name: 'AppMetrics'
    metrics_path: '/observability/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Capital Calculator'